---

kind: pipeline
type: docker
name: default

steps:
  - name: build amd64
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: denniskcheung/jenkins-ansible-python3-dind
      tags:
        - latest
        - lts
      platform:
        - linux/amd64
